name: MineTG # Имя плагина
version: ${project.version} # Версия плагина
api-version: 1.13
description: Управление сервером MineCraft через бота Telegram # Описание плагина
author: deade # Автор плагина
website:
main: ru.deade.minetg.MineTG # Путь к главному классу (тому, который наследует JavaPlugin)
commands:
    list:
        description: Проверка
        usage: /list
